### PR TITLE
support for location url matching modifiers

### PR DESCRIPTION
**Pull request by hdknr**
http://nginx.org/en/docs/http/ngx_http_core_module.html#location

### CODE REVIEW

**Comment by diracdeltas** [comment]
I had the same issue and so I tried this pull request. However, the test cases do not pass. I've fixed them here: https://github.com/diracdeltas/nginxparser/commit/5c7efa3e02c8cfa3b3316b6a0c31235cdf256e16

**Comment by fatiherikli** [comment]
Thanks :+1:

**Comment by fatiherikli** [comment]
Also I pulled your changes @diracdeltas. Thanks

**Comment by diracdeltas** [comment]
Thanks, but it looks like my test fix is not on master. Maybe you forgot to push?

**Pull request merged**
